### ISSUE TITLE
Interface 'NuxtApp' incorrectly extends interface 'Vue'. Types of property '$loading' are incompatible.

### ISSUE THREAD

**Issue by finntenzor** [nuxt-community/typescript-template#175]
### Version

[v2.12.1](https://github.com/typescript-template/releases/tag/v2.12.1)

### Reproduction link

[https://github.com/finntenzor/congenial-parakeet](https://github.com/finntenzor/congenial-parakeet)

### Steps to reproduce

npx create-nuxt-app akblog
cd akblog
yarn dev

### What is expected ?

Runs successfully

### What is actually happening?

119:18 Interface 'NuxtApp' incorrectly extends interface 'Vue'.
  Types of property '$loading' are incompatible.
    Type 'NuxtLoading' is not assignable to type '(options: LoadingServiceOptions) => ElLoadingComponent'.
      Type 'DefaultNuxtLoading' is not assignable to type '(options: LoadingServiceOptions) => ElLoadingComponent'.
        Type 'DefaultNuxtLoading' provides no match for the signature '(options: LoadingServiceOptions): ElLoadingComponent'.
    117 | }
    118 |
  > 119 | export interface NuxtApp extends Vue {
        |                  ^
    120 |   $options: NuxtAppOptions
    121 |   $loading: NuxtLoading
    122 |   context: Context

i Version: typescript 3.8.3

### Additional comments?

Actually, "yarn build" doesn't work, either.

119:18 Interface 'NuxtApp' incorrectly extends interface 'Vue'.
  Types of property '$loading' are incompatible.
    Type 'NuxtLoading' is not assignable to type '(options: LoadingServiceOptions) => ElLoadingComponent'.
      Type 'DefaultNuxtLoading' is not assignable to type '(options: LoadingServiceOptions) => ElLoadingComponent'.
        Type 'DefaultNuxtLoading' provides no match for the signature '(options: LoadingServiceOptions): ElLoadingComponent'.
    117 | }
    118 | 
  > 119 | export interface NuxtApp extends Vue {
        |                  ^
    120 |   $options: NuxtAppOptions
    121 |   $loading: NuxtLoading
    122 |   context: Context

 FATAL  Nuxt build error                                                                                                                                                          09:02:33  

  at WebpackBundler.webpackCompile (node_modules\@nuxt\webpack\dist\webpack.js:5351:21)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at WebpackBundler.build (node_modules\@nuxt\webpack\dist\webpack.js:5300:5)
  at Builder.build (node_modules\@nuxt\builder\dist\builder.js:5602:5)
  at Object.run (node_modules\@nuxt\cli\dist\cli-build.js:104:7)
  at NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:2759:7)

   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/typescript-template/issues/c56">#c56</a>)</em></sub></div>

**Comment by finntenzor** [comment]
It seems like I used the UI framework ElementUI which cause this problem. But I don't have any idea to solve it.
